name: test
on:
  pull_request:
    paths-ignore: [ '**.md' ]
  push:
    branches:
      - 'main'
    paths-ignore: [ '**.md' ]
env:
  go-version: 1.13
  cache-version: 1
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: arduino/setup-protoc@v1
      - run: make validate-generated